name: MasterDeployCI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Create Chrome dist ZIP
        run: |
          cd dist
          zip -r ../I-notes-extension.zip .
          cd ..
      - name: Create Firefox add-on ZIP
        run: |
          zip -r I-notes-addon.zip .

      - name: Upload I-notes-extension.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: I-notes-extension
          path: I-notes-extension.zip

      - name: Upload I-notes-addon.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: I-notes-addon
          path: I-notes-addon.zip
