name: MasterDeployCI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Create dist ZIP
        run: |
          cd dist
          zip -r ../dist.zip .
          cd ..

      - name: Upload dist.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-zip
          path: dist.zip
